"""initial schema: papers, collections, extraction_jobs, query_log

Revision ID: 3f7d443f5035
Revises:
Create Date: 2026-08-12 11:36:25.522934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f7d443f5035"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("graphrag_answer", sa.Text(), nullable=True),
        sa.Column("vanilla_answer", sa.Text(), nullable=True),
        sa.Column("retrieved_nodes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "user_feedback", sa.Enum("good", "bad", "none", name="user_feedback"), nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("arxiv_id", sa.Text(), nullable=True),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("pdf_path", sa.Text(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ingestion_status",
            sa.Enum("pending", "processing", "completed", "failed", name="ingestion_status"),
            nullable=False,
        ),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("arxiv_id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_index(op.f("ix_papers_collection_id"), "papers", ["collection_id"], unique=False)
    op.create_index(
        op.f("ix_papers_ingestion_status"), "papers", ["ingestion_status"], unique=False
    )
    op.create_table(
        "extraction_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "extracting_entities",
                "extracting_relations",
                "resolving_entities",
                "writing_graph",
                "completed",
                "failed",
                name="job_status",
            ),
            nullable=False,
        ),
        sa.Column("entities_found", sa.Integer(), nullable=False),
        sa.Column("relations_found", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_jobs_paper_id"), "extraction_jobs", ["paper_id"], unique=False
    )
    op.create_index(op.f("ix_extraction_jobs_status"), "extraction_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extraction_jobs_status"), table_name="extraction_jobs")
    op.drop_index(op.f("ix_extraction_jobs_paper_id"), table_name="extraction_jobs")
    op.drop_table("extraction_jobs")
    op.drop_index(op.f("ix_papers_ingestion_status"), table_name="papers")
    op.drop_index(op.f("ix_papers_collection_id"), table_name="papers")
    op.drop_table("papers")
    op.drop_table("query_log")
    op.drop_table("collections")
    # ### end Alembic commands ###
